# **AICP INTERNSHIP TASK**

## **WEEK 1**

In [1]:
import numpy as np
from numpy import random

### **- Task 1/7**
Write a NumPy program to create an array of all even integers from 30 to 70.

In [2]:
array = np.arange(30,71,2)

In [3]:
array 

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

### **- Task 2/7**
Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [4]:
num = np.random.normal(loc=0.0, scale=1.0, size=(15,))

In [5]:
num

array([-0.62911824,  0.75459235, -0.94888161,  0.92134144, -1.90570544,
       -1.28756059,  0.09659177, -0.13985912,  0.92401631,  0.67035498,
       -0.77455937, -0.75678125, -0.36077009, -0.76661228, -2.10069751])

### **- Task 3/7**
How to compute the cross-product of two matrices in NumPy?

In [6]:
matrix1 = np.array([3, 4])

In [7]:
matrix2 = np.array([[2, 6], [7, 8]])

In [8]:
matrix1

array([[1, 2],
       [3, 4]])

In [28]:
matrix2

array([[2, 6],
       [7, 8]])

In [9]:
product = np.cross(matrix1, matrix2)

In [10]:
product

array([ 2, -4])

### **- Task 4/7**
How to compute the determinant of an array using NumPy?

In [11]:
matrix = np.array([[2, 1], [4, 5]])

In [12]:
determinant = np.linalg.det(matrix)

In [13]:
determinant

6.0

### **- Task 5/7**
How to create a 3x3x3 array with random values using NumPy?

In [14]:
randarray = np.random.rand(3, 3, 3)

In [15]:
randarray

array([[[0.96918492, 0.77179364, 0.83682752],
        [0.24933882, 0.13174002, 0.36908409],
        [0.75768993, 0.76657271, 0.31237797]],

       [[0.17838595, 0.66908738, 0.64458544],
        [0.6589266 , 0.38423105, 0.6386533 ],
        [0.68544138, 0.95156144, 0.88354655]],

       [[0.80236855, 0.06652327, 0.31611015],
        [0.5672751 , 0.17166901, 0.8626153 ],
        [0.03660395, 0.32033393, 0.65126635]]])

### **- Task 6/7**
How to create a 5x5 array with random values and find the minimum and maximum values using
NumPy?

In [16]:
array = np.random.rand(5, 5)

In [17]:
array

array([[0.50886713, 0.56877164, 0.40143625, 0.89373867, 0.00506519],
       [0.6164433 , 0.23662475, 0.2613882 , 0.73488106, 0.8438975 ],
       [0.77758317, 0.34158649, 0.98040552, 0.56186828, 0.80123689],
       [0.29812199, 0.82632189, 0.16762767, 0.42525921, 0.0420796 ],
       [0.14467413, 0.90636146, 0.56156105, 0.4998305 , 0.21669499]])

In [18]:
min_value = np.min(array)
max_value = np.max(array)

In [19]:
print("Minimum value:", min_value)

Minimum value: 0.005065188143084209


In [20]:
print("Maximum value:", max_value)

Maximum value: 0.9804055236864606


### **- Task 7/7**
How to compute the mean, standard deviation, and variance of a given array along the second axis in
NumPy?

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [22]:
mean = np.mean(arr, axis=1)

In [23]:
print("Mean:", mean)

Mean: [2. 5. 8.]


In [24]:
std = np.std(arr, axis=1)

In [25]:
print("Standard deviation:", std)

Standard deviation: [0.81649658 0.81649658 0.81649658]


In [26]:
variance = np.var(arr, axis=1)

In [27]:
print("Variance]:", variance)

Variance]: [0.66666667 0.66666667 0.66666667]


**Thankyou :)**